mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import get_user_model
from rest_framework import routers, serializers


class UserSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = get_user_model()
        fields = ('url', 'username', 'email', 'is_staff')


router = routers.DefaultRouter()


urlpatterns = [
    url(r'^',  include('polls.urls'), name='index'),
    url(r'^api/', include('polls.urls', namespace='polls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

polls/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from .views import QuestionViewSet, ChoiceViewSet
from . import views

app_name = 'polls'

router = routers.DefaultRouter()
router.register(r'questions', QuestionViewSet)
router.register(r'choice', ChoiceViewSet)

schema_view = get_swagger_view(title='Polls API')

urlpatterns = [
    #  /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /polls/id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /polls/id/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # /polls/id/vote
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # login view
    url(r'^login/$', auth_views.login, {'template_name': 'polls/login.html', 'redirect_field_name': '/'}, name="login"),
    # logout view
    url(r'^logout/$', auth_views.logout, {'template_name': 'polls/logout.html'}, name='logout'),

    url(r'^signup/$',views.SignupView.as_view(), name='signup'),
    # swagger
    url(r'^docs/', schema_view),
]

urlpatterns += router.urls

polls/models.py
from django.db import models
from django.utils import timezone as d_timezone
from django.contrib.auth.models import AbstractUser
from django.core.cache import cache
from mysite import settings
import datetime


class PollUser(AbstractUser):

    def last_seen(self):
        return cache.get('seen_%s' % self.username)

    def online(self):
        if self.last_seen():
            time_interval = time = d_timezone.now() - d_timezone.timedelta(seconds=settings.USER_ONLINE_TIMEOUT)
            if self.last_seen() < time_interval:
                return False
            else:
                return True
        else:
            return False


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=d_timezone.now)
    asker = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "[@{}]: {}".format(self.pub_date, self.question_text)

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"

    def __unicode__(self):
        return "{} {}".format(self.question_text, self)

    def was_published_recently(self):
        now = d_timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def save(self, *args, **kwargs):
        super(Question, self).save(*args, **kwargs)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    users = models.ManyToManyField(PollUser)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import widgets
from django.core.validators import validate_email


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=100, min_length=3, required=True)
    first_name = forms.CharField(min_length=3, max_length=30, required=True)
    last_name = forms.CharField(min_length=3, max_length=30, required=True)
    email = forms.CharField(min_length=3, max_length=50, required=True, validators=[validate_email])
    password = forms.CharField(widget=widgets.PasswordInput(), required=True, min_length=5, max_length=32)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from rest_framework.permissions import AllowAny
from rest_framework.decorators import list_route
from rest_framework.response import Response
from .models import Question, Choice, PollUser
from .serializers import QuestionSerializer, ChoiceSerializer
from .forms import UserRegistrationForm

# REST


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    permission_classes = [AllowAny]

    @list_route(permission_classes=[AllowAny], url_path='count')
    def count(self, request):
        return Response({'count': Question.objects.count()})

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user if self.request.user is not None else "unknown")


class ChoiceViewSet(viewsets.ModelViewSet):
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer
    permission_classes = [AllowAny]


# WEB APP

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:2]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class SignupView(FormView):
    template_name = 'polls/signup.html'
    form_class = UserRegistrationForm
    success_url = '/login'

    def form_valid(self, form):
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = PollUser.objects.create_user(username=cleaned_data['username'],
                                                first_name=cleaned_data['first_name'],
                                                last_name=cleaned_data['last_name'],
                                                email=cleaned_data['email'],
                                                password=cleaned_data['password'])
            try:
                user.save()
            except Exception as saving_ex:
                print(saving_ex)
            finally:
                return super(SignupView, self).form_valid(form)


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def question_channel(request):
    user_model = get_user_model()
    online_users = [username for username in user_model.objects.all() if username.online()][:5]
    return render(request, "polls/index.html", {
        'online_users': online_users,
    })

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
        <title>{% block title %}{% endblock %}</title>

        <!-- CSS  -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="{% static 'polls/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{% static 'polls/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <style>
            body {
                display: flex;
                min-height: 100vh;
                flex-direction: column;
            }

            main {
                flex: 1;
            }
        </style>
    {% endblock %}
</head>
<body>
<main>
    {% block header %}

        <nav class="light-blue lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="{%  url 'polls:index' %}" class="brand-logo">
                    Polls
                </a>
                <ul id="dropdown2" class="dropdown-content">
                    <li><a href="{% url 'polls:index' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'polls:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'polls:login' %}">Login</a></li>
                        <li><a href="{% url 'polls:signup' %}">Signup</a></li>
                    {% endif %}
                    <li><a href="#">Empty</a></li>

                </ul>
                <a class="btn dropdown-button right hide-on-med-and-down" href="#!" data-activates="dropdown2">Hi
                    {% if request.user.is_authenticated %}
                        {{ request.user }}
                    {% else %}
                        anonymous
                    {% endif %} !<i class="mdi-navigation-arrow-drop-down right"></i></a>

                <ul id="nav-mobile" class="side-nav">
                    <li><a href="#">Navbar Link</a></li>
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            </div>
        </nav>
    {% endblock %} {# end block header #}
    {% block containter %}

        <div class="section no-pad-bot" id="index-banner">
            <div class="container">
                {% block maincontent %}
                {% endblock %}
            </div>
        </div>

        {% block latest_answer_n_users %}
        {% endblock %}

    {% endblock %} {# end block container #}
</main>

{% block footer %}
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">A Company</h5>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}{# end block footer #}
<!--  Scripts-->
{% block scripts %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'polls/js/materialize.js' %}"></script>
    <script src="{% static 'polls/js/init.js' %}"></script>
{% endblock %}

</body>
</html>

polls/templates/polls/connected_users.html
{# TODO #}
{% block connected_users %}
    <div class="col-sm-2 sidenav">
        <h3>There
            {% if online_users.count == 1%}is
            {% else %}are
            {% endif %}
            {{ online_users|length}} connected user{{ online_users|pluralize }}</h3>
        {% for online_user in online_users %}
            <div class="well">
                <p><span class="glyphicon glyphicon-eye-open"></span> {{ online_user.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %}
    Detail page for {{ question.id }}
{% endblock %}

{% block maincontent %}
    <h2>{{ question.question_text }}</h2>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p> {% endif %}
    <div class="container">
        <div class="section">

            <form action="{% url 'polls:vote' question.id %}" method="post" class="col s12">
                <div class="radio">
                    {% csrf_token %}
                    {% for choice in question.choice_set.all %}
                        <p>
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"
                            {% if not request.user.is_authenticated %}
                                disabled
                            {% endif %}
                            />
                            <label class="label label-default" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label> <br />
                        </p>
                    {% endfor %}
                </div>
                <br/><br/>
                <input type="submit" class="waves-effect waves-light btn" value="Vote"/>
            </form>
        </div>
    </div>

    <br/><br/>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
    Polls
{% endblock %}

{% block maincontent %}
    <br><br>
    <div class="row">
        <div class="col s12 m6">
            <h1 class="header center orange-text">Polls website</h1>
            <div class="row center">
                <h5 class="header col s12 light">The world's useless website ever</h5>
            </div>
        </div>

        <div class="col s12 m6">
            <div id="container">

            </div>
            {% render_bundle 'main' %}
        </div>
    </div>

    <br><br>



{% endblock %}

{% block latest_answer_n_users %}
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            {% if latest_question_list %}

                {% for question in latest_question_list %}
                    {% include 'polls/question_card.html' with t_question_date=question.pub_date t_question_text=question.question_text  %}
                {% endfor %}
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            <div class="col s12 m4">

                <div class="section">
                    <form id="onlineusers_form">
                        <input id="hidden_username" type="hidden" value="{{ request.user.username }}" />
                        <input id="session_key" type="hidden" value="{{ request.session.session_key }}" />

                        <ul id="online_users" class="collection with-header">
                            <li class="collection-header"><h5>Online users</h5></li>
                        </ul>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'polls/js/web_socket.js' %}" ></script>
    <script type="text/javascript" src="{% static 'polls/js/reconnecting-websocket.min.js' %}" ></script>
{% endblock %}

polls/templates/polls/login.html
{% extends "polls/base.html" %}

{% block title %}
    Login
{% endblock %}


{% block maincontent %}
    <h2>{{ Login}}</h2>

    {% if form.errors %}
        <p>Your username ad password didn't match. Please try again</p>
    {% endif %}

    <form method="post" action="{% url 'polls:login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <a class="waves-effect waves-light btn">
            <input type="submit" value="login" />
        </a>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    <br/>    <br/>    <br/>

{% endblock %}

polls/templates/polls/logout.html
{% extends "polls/base.html" %}

{% block maincontent %}

<h1 class="label-success">Logged out</h1>

{% endblock %}

polls/templates/polls/question_card.html
<div class="col s12 m4">
    <div class="icon-block">
        <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
        <h5 class="center">
            <a href="{% url 'polls:detail' question.id %}">
                {{ t_question_text }}
                <span class="badge"></span>
            </a>
        </h5>
        <p class="light">{{ t_question_date}}</p>
    </div>
</div>

polls/templates/polls/registration.html
{% extends 'polls/base.html' %}
{% block title %} Register{% endblock %}
{% block maincontent %}
    <form action="/your-name/" method="post">
        {% csrf_token %}
        {{ form }}
        {# TODO #}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block title %}
    Results for question {{ question.id }}
{% endblock %}

{% block maincontent %}
    <div class="container">
        <h1>Results</h1>
    </div>

    <ul class="collection">
        <li class="collection-header"><h4>{{ question.question_text }}</h4></li>
        {% for choice in question.choice_set.all %}
            {% if forloop.counter == 1 %}
                <li class="collection-item active">
                    <b>{{ choice.choice_text }}</b>
                    wins with vote{{ choice.votes|pluralize }}:
                    <span class="new badge white green-text" data-badge-caption="!">{{ choice.votes }}</span> </li>
            {% else %}
                <li class="collection-item">{{ choice.choice_text }} vote{{ choice.votes|pluralize }}:
                    <span class="badge">{{ choice.votes }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/signup.html
{% extends 'polls/base.html' %}
{% block title %} Register{% endblock %}
{% block maincontent %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}